# /flux/boot/traefik/helmrepo.yaml
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: ot-helm
  namespace: flux-system
spec:
  interval: 1m0s
  url: https://ot-container-kit.github.io/helm-charts/
---
# /flux/boot/traefik/helmrelease.yaml
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: redis-operator
  namespace: redis-ops
spec:
  chart:
    spec:
      chart: redis-operator
      sourceRef:
        kind: HelmRepository
        name: ot-helm
      version: latest
  install:
    createNamespace: true
  interval: 1m0s