apiVersion: apps/v1
kind: Deployment
metadata:
  name: likes-service-deployment
  labels:
    app: 
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: likeservice
        image: jguillaumes/likes-service:latest
        ports:
        - containerPort: 80